---
kind: pipeline
name: build-and-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: clone-drone-repo
    image: docker:git
    commands:
      - git clone --recursive https://github.com/drone/drone.git drone
  - name: build-drone-oss
    image: golang:1.12
    commands:
      - (cd drone && ../build.sh)
      - (cd drone && ../tags.sh) > .tags
    environment:
      CGO_ENABLED: 1
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: direct
  - name: build-standard-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: docker/Dockerfile.server.linux.amd64
      password:
        from_secret: docker_password
      repo: garykim/drone-oss
      username: garykim
    when:
      branch:
        - master
  - name: set-privacy-image-tags
    image: docker:git
    commands:
      - (cd drone && ../tags.sh -privacy) > .tags
  - name: build-privacy-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: docker/Dockerfile.server.linux.amd64.privacy
      password:
        from_secret: docker_password
      repo: garykim/drone-oss
      username: garykim
    when:
      branch:
        - master
---
kind: secret
name: docker_password
data: KQkS8DdTZoLTslToRuhxsXRxngGTht3U0+QmlaqSygzqbJSy0CZgL1Iv4FGoH0kbLQ==
