---
kind: pipeline
name: build-and-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: clone-drone-repo
    image: alpine:3.9
    commands:
      - apk add git
      - git clone --recursive https://github.com/drone/drone.git drone

  - name: build-drone-oss
    image: golang:1.12
    commands:
      - cd drone
      - "go build -tags oss -ldflags \"-extldflags \\\\\"-static\\\\\"\" -o release/linux/amd64/drone-server github.com/drone/drone/cmd/drone-server"
      - cd ..
      - git log -1 --format=%H > memorycommit
    environment:
      CGO_ENABLED: 1
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: direct

  - name: build-standard-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: docker/Dockerfile.server.linux.amd64
      tags: linux-amd64
      password:
        from_secret: docker_password
      repo: garykim/drone-oss
      username:
        from_secret: docker_username
    when:
      event:
        - push

  - name: build-privacy-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: docker/Dockerfile.server.linux.amd64.privacy
      tags: linux-amd64-privacy
      password:
        from_secret: docker_password
      repo: garykim/drone-oss
      username:
        from_secret: docker_username
    when:
      event:
        - push
